### ISSUE TITLE
Get an error when running migrations for the first time

### ISSUE THREAD

**Issue by GregBaugues** [TwilioDevEd/account-verification-laravel#2]
I cloned the repo and followed the instructions in the README. I get this error when running migrations for the first time: 

```
[PDOException]
SQLSTATE[08006] [7] FATAL:  role "password=''" does not exist
```

@nebtrx @mcelicalderon

**Comment by mcelicalderon** [comment]
@GregBaugues I have updated the `.env.example` file to include your database information. You should specify your postgres db username and password in the `.env` file. Remember to copy the file before running the migrations. You can also leave the username empty to use postgres default user and the same for password if the user has no password. Please let me know if you still have problems with this

**Comment by mcelicalderon** [comment]
@GregBaugues Closing this as the .env.example file was updated to include db information. Let me know if you have any other issues.
